LINKEDIN_USERNAME             = "jit@itobuz.com"
LINKEDIN_PASSWORD             = "Abcd@1234"
LINKEDIN_POST_DATA_FILENAME   = 'post_data.csv'
LINKEDIN_POST_DATA_PATH       = './data/linkedin_data'
LINKEDIN_IMAGE_DATA_PATH      = './data/linkedin_data/linkedin_images'
LINKEDIN_LOGIN_PAGE_LINK      = "https://www.linkedin.com/login"
CHROME_DRIVER_PATH            = "/opt/homebrew/bin/chromedriver"
PROFILE_URL                   = "https://www.linkedin.com/company/itobuz-technologies-pvt-ltd/posts/?feedView=all"
INSTAGRAM_USERNAME            = "itobuztechnologies"
INSTAGRAM_IMAGE_DATA_PATH     = "./data/instagram_data/instagram_images"
INSTAGRAM_POST_DATA_PATH      = "./data/instagram_data/instagram_post_data.json"